package main

const (
	ACL_DEFINITION = `[
    { "FunctionName" : "requestRewardPoints" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getRequestDetailByRequestID" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getAllRewardRequestDetails" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getAllBurnRequestDetails" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "approveRequest" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "setMembershipIdentities" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getAllMemberDetails" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getMemberDetailsByMemberID" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "burnRewardPoints" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getRewardPoints" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getAllACLConditions" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getACLConditionsByFuncAndOrg" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "updatePurchase" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getPurchaseDetailsByPurchaseID" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getAllPurchaseDetails" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "transferRewardPoints" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "quickTransfer" , 
                            "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                                                  {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                                                  {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getTransferDetailbyTransferID" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getAllTransferDetails" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } , 
    { "FunctionName" : "getRewardPointsBalanceByMemberID" , 
      "ConditionsList": [   {"Org":"MARRIOTT","Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"ACCOR", "Dept":"BOOKING_UNIT","Role":"ADMIN"}, 
                            {"Org":"LUFTHANSA", "Dept":"BOOKING_UNIT","Role":"ADMIN"}] } 

                    ]`
)
